sudo: true

language: rust
rust:
  - nightly

install:
# Libsodium
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.12.tar.gz
  - tar -xvf libsodium-1.0.12.tar.gz
  - cd libsodium-1.0.12
  - ./configure
  - make
  - make check
  - sudo make install
  - sudo ldconfig

# RustFmt
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
  - rustfmt --version

script:
  - cargo fmt -- --write-mode=diff -v
  - cargo build
  - cargo test
