language: rust
rust:
  - stable

install:
# Libsodium
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.12.tar.gz
  - tar -xvf libsodium-1.0.12.tar.gz
  - cd libsodium-1.0.12
  - ./configure
  - make
  - make check
  - sudo make install
  - sudo ldconfig
  - sudo apt install libncursesw5-dev pkg-config libssl-dev xorg-dev

script:
  - cargo build
  - cargo test

notifications:
  webhooks:
    secure: "Nb/mr1VhoHDM0ngz38bMT3dqVwoia8pC2kBf5ooQh6Omvr8uwTvsvHZ6J6IUNKWNazu4kObJk153rWP/noDD/UW3TXaQCIHsFsLA4bzeaQWcxEsQTn5Wdd1JjVOtbstT2lug6dQEHuaWLiWRRO/M5ABeZIrMp3Ulq5SwKS6KbNDN+YsbiGMNI9U55bPQlrGDxrLLerBrTvxX4Ky9KVAlDxYsxMaMjjEpY1QC1orwksdCpzzI/EPjEcAKudI5vP8FDQbsCOUa3rjLo4ELQWoGR4MCMYSN2oDXM1BP+1b55q43BKqAIaOXGGCht9NdEKkBh5RhrQNrpuWDz1sAWNW6uwyYoNfYk2dvCmKDRRxVFxxYK28oNwWGSvR1cYNlQfq6kV3x2gJCa/3fQQ+yIxq7NzLlBfKnZgjUNvhxEIJchv5ukachKbtatt8B9GFkaZkWgQopVSm8+H1CSPm3wCJr+G5uudX0dS2UgBwfg2WzAFhWg3b4bHYmC3/lUYLpBR8WcBQCpW68scxNb4bfqQvxfjebPdMgujRwZ2MStuMbWqxUEN/5vXjz04oVCLrIQbj/9Qqlkdbu3vmmo1sIioVFme/AocXrpXLWdiEgRjmCe2ZI9tNDNXOZ56tYyClFk8kbi36GENwYHQlJPgse4sDMO/xKvbzfXmLgE1uS9H5zQF8="

